services:
  newcastle_racing_ai:
    image: newcastle-racing-ai
    build: .
    container_name: newcastle-racing-ai
    volumes:
      - ./newcastle_racing_ai:/workspace/newcastle_racing_ai
      - ./newcastle_racing_ai_msgs:/workspace/newcastle_racing_ai_msgs
      - zed-settings:/usr/local/zed/settings
      - zed-resources:/usr/local/zed/resources
    ports:
      - "9090:9090"
    stdin_open: true
    tty: true
    privileged: true # Enable USB support. Only needed for mods==real to use the ZED camera
    deploy: 
      resources:
        reservations:
          devices: # Enable GPU support. Only needed for mods==real to use the ZED camera
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command:
      - mode:=real # [sim, real] - Determines wheter to launch the ros bridge (for the simulation) or the ZED node
  fsds:
    image: fsds-ros
    build: ./Formula-Student-Driverless-Simulator
    container_name: fsds-ros
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - newcastle_racing_ai
    command:
      - "--fsds-ip"
      - "host.docker.internal" # This refers to the host running the Docker container
      - "--ros-ip"
      - "newcastle_racing_ai" # This refers to the service name in the docker-compose file
      - "--timestep"
      - "5"
      - "--sensors" # Add or remove sensors as needed
      - "camera"
      - "depth"
      - "lidar"
      - "imu"
      - "odom"
      - "track"
      - "--receivers" # Add or remove receivers as needed
      - "reset"
      # - "control" # WARNING: You can only control the car from ROS or with the Keyboard, not both at the same time
    stdin_open: true
    tty: true

volumes:
  zed-settings:
  zed-resources:
